fixat maven

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -2,42 +2,48 @@ name: 'Maven Build'
 
 on: push
 
-
-
 jobs:
   build:
     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Set up corretto17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-          cache: maven
+    services:
+      mysql:
+        image: mysql:8.0
+        ports:
+          - 3306:3306
+        env:
+          MYSQL_ROOT_PASSWORD: 'AgueroAguero123!'
+          MYSQL_DATABASE: 'book_author_db'
+        options: >-
+          --health-cmd 'mysqladmin ping --silent'
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 3
 
-      - name: Build with Maven
-        run: mvn -B package --file pom.xml
+  steps:
+    - name: Checkout
+      uses: actions/checkout@v4
 
+    - name: Set up Java
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
+        cache: maven
 
+    - name: Wait for MySQL to be ready
+      run: |
+        for i in {30..0}; do
+          if mysqladmin ping -h127.0.0.1 -uroot -p'AgueroAguero123!' --silent; then
+            break
+          fi
+          echo 'MySQL init process in progress...'
+          sleep 1
+        done
+        if [ "$i" = 0 ]; then
+          echo >&2 'MySQL init process failed.'
+          exit 1
+        fi
 
-  publish-job:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout av kod
-        uses: actions/checkout@v4
-      - name: Setup av Java
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-      - run: mvn --batch-mode --update-snapshots verify
-      - run: mkdir staging && cp target/*.jar staging
-      - name: Laddar upp artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: Package
-          path: staging
+    - name: Build with Maven
+      run: mvn -B package --file pom.xml
